### ISSUE TITLE
Uncommented commit regarding data range

### ISSUE THREAD

**Issue by paulmueller** [DC-analysis/fcswrite#1]
I am confused by this commit:

https://github.com/ZELLMECHANIK-DRESDEN/fcswrite/commit/4860ac2ef92691a2f8129fb3e534fc094554b686

- Where does "maximum[a.u.]" come from? I believe this setting requires a new `compat_*` parameter and it should be explained what it does and where it does it. Is "maximum[a.u.]" a universal identifier for something?
- Setting the pnrange to 100 for "Deformation" is wrong in my opinion. This should only happen for the axes that have values between 0 and 1 and also only when `compat_percent` is set to `True`. Also "Deformation" is a very special case (what about "Circularity"?)

I believe the best way to deal with this is to check for the compatibility modes (and e.g. the list `toscale`) in this for loop.

**Comment by phidahl** [comment]
You are right...
- "maxium[a.u.]" is the ending that all Fluorescence data colums share. They are not plotted properly if the range is not defined. I choose 2**15 as range to cover the whole dynamic range of the recorded data (int16)
- this should only be done if compat_percent is True. right.

I'll change it..

**Comment by paulmueller** [comment]
Thanks,

- please explain `compat_fixed_range_for_fl` in the docstring and consider using something shorter such as `compat_max_int16` (the reference to fluorescence only applies to your special case and you are only setting the maximum value and not the range).

- Is there potentially a space in "maxium[a.u.]"? If so, then you might get problems if `compat_chn_names` is set to `False`! It might be worth looking for a different way to determine whether the maxiumum should be int16.

- in this line here:

    https://github.com/ZELLMECHANIK-DRESDEN/fcswrite/commit/35ebd0b94adfa68e11e5e520ea5706755b014529#diff-33b59ab26583ef3b49cd34c21366b95eR125

    You are still checking for explicit strings that are special cases. I would prefer something that first checks if `compat_percent` is `True` (and then compares `i` against the `toscale` list to determine whether we have to set 100).

**Comment by paulmueller** [comment]
I reworked the compatibility modes in the above commit. I think this should be fine now. Let me know if I broke something.
