### ISSUE TITLE
Wrong header if data segment ends after the 99,999,999th byte

### ISSUE THREAD

**Issue by joseph-sch** [DC-analysis/fcswrite#2]
If the data segment ends beyond the 99,999,999th byte, its last byte cannot be written in the header within the allocated 8 bytes.

The specification (at least for version 3.1) specifies that in that case _both_ the data first byte and data last byte have to be set to 0.

I could send a pull request eventually, but in the meantime, I think the patch should be something like:

```
    if 256+ltxt+len(DATA)-1 <= 99_999_999:
        datafirst = '{0: >8}'.format(256+ltxt)
        datalast = '{0: >8}'.format(256+ltxt+len(DATA)-1)
    else:
        datafirst = '{0: >8}'.format(0)
        datalast = '{0: >8}'.format(0)
```

**Comment by paulmueller** [comment]
It appears that this feature was introduced in version 3.0 of the file format: https://onlinelibrary.wiley.com/doi/pdf/10.1002/%28SICI%291097-0320%2819970601%2928%3A2%3C118%3A%3AAID-CYTO3%3E3.0.CO%3B2-B
The size of the dataset must be stored in the text segment in this case.

I think we also need to test this functionality (e.g. with `fcm.loadFCS`). Are you still planning to submit a PR?
