### ISSUE TITLE
FCS output is corrupted if the header size is larger than 4096 bytes

### ISSUE THREAD

**Issue by joseph-sch** [DC-analysis/fcswrite#4]
If the number of columns is large, the file can be corrupted because the program allocates a fixed size (4096 bytes) to the header. 

The following code will create files with various header sizes and showing the issue:

```python
import fcswrite
import pandas as pd
import numpy as np
for num_cols in [45, 50, 55, 60]:
    df = pd.DataFrame(columns=['my_possibly_long_column_name' + str(i) for i in range(num_cols)],
                data=np.random.randn(1000, num_cols))
    fcswrite.write_fcs('test_header_size_' + str(num_cols) + '.fcs', df.columns.tolist(), data=df.values)
```

Thees screenshots in a Hex editor show the issue when the header reaches into byte 4352 (0x1100):

This file is OK, with blank space left between the end of the header and the beginning of data at byte 0x1100:

![fcswrite_header_size_ok](https://user-images.githubusercontent.com/11660030/49359679-8b4cb480-f6df-11e8-90ce-038507340066.PNG)

This file is corrupted, with the header continuing into the area where the data should reside:

![fcswrite_header_size_not_ok](https://user-images.githubusercontent.com/11660030/49359682-8c7de180-f6df-11e8-8fae-01f9a97ff51d.PNG)

**Comment by joseph-sch** [comment]
An exception can be raised if the header is larger than the allocated header size:

```python
    if len(TEXT) > ltxt:
        raise ValueError('Header text {0} longer than {1} not implemented'.format(len(TEXT), ltxt))
```

And the allocated header size could also be increased, but neither of these changes would be totally satisfying.

The full fix would be to construct the header with unknown `$BEGINDATA` and `$ENDDATA` entries, then evaluate the size of the header and finally update the `$BEGINDATA` and `$ENDDATA` entries of the header.

**Comment by paulmueller** [comment]
Thanks for reporting this bug! Yes, a full fix would be the only acceptable solution. I might get around to implementing this within the next two weeks.

Unless you would like to fix it yourself and create a PR. Please let me know whether you have the time for that.
